[package]
name    = "fixplay-tauri"
version = "0.1.0"
edition = "2021"

[lib]
name       = "fixplay_tauri"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
fixplay-core      = { path = "../crates/fixplay-core" }
fixplay-flashrom  = { path = "../crates/fixplay-flashrom" }
fixplay-uart      = { path = "../crates/fixplay-uart" }
tauri         = { version = "2", features = [] }
serde         = { workspace = true }
serde_json    = { workspace = true }
tokio         = { workspace = true }
tracing       = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
anyhow        = { workspace = true }
serialport    = "4"
