version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/src-tauri/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/crates/fixplay-core/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/crates/fixplay-flashrom/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/crates/fixplay-uart/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/crates/fixplay-i2c/'
    schedule:
      interval: 'weekly'
