import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node, __MOCK_MODE__: 'readonly' },
    },
  },
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: { parser: ts.parser },
    },
  },
  {
    // Honor the repo's `_`-prefix convention for intentionally-unused bindings.
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    ignores: [
      'build/',
      '.svelte-kit/',
      'dist/',
      'src-tauri/',
      'target/',
      // typesafe-i18n generated files (regenerated by `npm run i18n` / `npm run check`)
      'src/lib/i18n/i18n-types.ts',
      'src/lib/i18n/i18n-svelte.ts',
      'src/lib/i18n/i18n-util.ts',
      'src/lib/i18n/i18n-util.async.ts',
      'src/lib/i18n/i18n-util.sync.ts',
    ],
  },
];
