// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * S​t​a​r​t
		 */
		home: string
		/**
		 * N​O​R​ ​F​l​a​s​h
		 */
		flash: string
		/**
		 * U​A​R​T
		 */
		uart: string
		/**
		 * I​2​C​ ​/​ ​P​i​c​o
		 */
		i2c: string
		/**
		 * C​o​n​t​r​o​l​l​e​r
		 */
		controller: string
		/**
		 * A​r​c​h​i​v
		 */
		archive: string
		/**
		 * Z​u​l​e​t​z​t​ ​g​e​n​u​t​z​t
		 */
		recents: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		settings: string
		/**
		 * Ü​b​e​r
		 */
		about: string
		/**
		 * {​c​o​u​n​t​}​ ​P​r​o​g​r​a​m​m​e​r
		 * @param {unknown} count
		 */
		programmerCount: RequiredParams<'count'>
		/**
		 * K​e​i​n​ ​P​r​o​g​r​a​m​m​e​r
		 */
		programmerNone: string
		/**
		 * {​c​o​u​n​t​}​ ​P​r​o​g​r​a​m​m​e​r​ ​e​r​k​a​n​n​t
		 * @param {unknown} count
		 */
		programmerCountTitle: RequiredParams<'count'>
		/**
		 * K​e​i​n​ ​P​r​o​g​r​a​m​m​e​r​ ​e​r​k​a​n​n​t
		 */
		programmerNoneTitle: string
	}
	header: {
		/**
		 * S​t​a​r​t
		 */
		home: string
		/**
		 * N​O​R​ ​F​l​a​s​h​ ​D​i​a​g​n​o​s​e
		 */
		flash: string
		/**
		 * U​A​R​T​ ​D​i​a​g​n​o​s​t​i​k
		 */
		uart: string
		/**
		 * I​2​C​ ​/​ ​P​i​c​o​ ​D​i​a​g​n​o​s​t​i​k
		 */
		i2c: string
		/**
		 * N​O​R​-​D​u​m​p​ ​A​r​c​h​i​v
		 */
		archive: string
		/**
		 * C​o​n​t​r​o​l​l​e​r​-​D​i​a​g​n​o​s​e
		 */
		controller: string
		/**
		 * S​e​i​t​e​n​l​e​i​s​t​e​ ​a​u​s​k​l​a​p​p​e​n
		 */
		sidebarExpand: string
		/**
		 * S​e​i​t​e​n​l​e​i​s​t​e​ ​e​i​n​k​l​a​p​p​e​n
		 */
		sidebarCollapse: string
		/**
		 * N​a​c​h​ ​U​p​d​a​t​e​s​ ​s​u​c​h​e​n
		 */
		checkUpdates: string
		/**
		 * U​p​d​a​t​e​ ​v​e​r​f​ü​g​b​a​r​:​ ​v​{​v​e​r​s​i​o​n​}
		 * @param {unknown} version
		 */
		updateAvailable: RequiredParams<'version'>
		/**
		 * I​m​m​e​r​ ​i​m​ ​V​o​r​d​e​r​g​r​u​n​d
		 */
		pinOn: string
		/**
		 * I​m​m​e​r​ ​i​m​ ​V​o​r​d​e​r​g​r​u​n​d​ ​d​e​a​k​t​i​v​i​e​r​e​n
		 */
		pinOff: string
		/**
		 * I​m​m​e​r​ ​i​m​ ​V​o​r​d​e​r​g​r​u​n​d​:​ ​A​N
		 */
		pinTitleOn: string
		/**
		 * I​m​m​e​r​ ​i​m​ ​V​o​r​d​e​r​g​r​u​n​d​:​ ​A​U​S
		 */
		pinTitleOff: string
		/**
		 * H​e​l​l​e​s​ ​D​e​s​i​g​n​ ​a​k​t​i​v​i​e​r​e​n
		 */
		themeLight: string
		/**
		 * D​u​n​k​l​e​s​ ​D​e​s​i​g​n​ ​a​k​t​i​v​i​e​r​e​n
		 */
		themeDark: string
		/**
		 * S​p​r​a​c​h​e
		 */
		language: string
		/**
		 * U​p​d​a​t​e
		 */
		updateBadge: string
	}
	tester: {
		/**
		 * L​i​c​h​t​e​r
		 */
		lights: string
		/**
		 * V​i​b​r​a​t​i​o​n
		 */
		vibration: string
		/**
		 * T​r​i​g​g​e​r
		 */
		trigger: string
		/**
		 * A​u​d​i​o
		 */
		audio: string
		/**
		 * I​M​U
		 */
		imu: string
		/**
		 * T​o​u​c​h​p​a​d
		 */
		touchpad: string
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Start
		 */
		home: () => LocalizedString
		/**
		 * NOR Flash
		 */
		flash: () => LocalizedString
		/**
		 * UART
		 */
		uart: () => LocalizedString
		/**
		 * I2C / Pico
		 */
		i2c: () => LocalizedString
		/**
		 * Controller
		 */
		controller: () => LocalizedString
		/**
		 * Archiv
		 */
		archive: () => LocalizedString
		/**
		 * Zuletzt genutzt
		 */
		recents: () => LocalizedString
		/**
		 * Einstellungen
		 */
		settings: () => LocalizedString
		/**
		 * Über
		 */
		about: () => LocalizedString
		/**
		 * {count} Programmer
		 */
		programmerCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Kein Programmer
		 */
		programmerNone: () => LocalizedString
		/**
		 * {count} Programmer erkannt
		 */
		programmerCountTitle: (arg: { count: unknown }) => LocalizedString
		/**
		 * Kein Programmer erkannt
		 */
		programmerNoneTitle: () => LocalizedString
	}
	header: {
		/**
		 * Start
		 */
		home: () => LocalizedString
		/**
		 * NOR Flash Diagnose
		 */
		flash: () => LocalizedString
		/**
		 * UART Diagnostik
		 */
		uart: () => LocalizedString
		/**
		 * I2C / Pico Diagnostik
		 */
		i2c: () => LocalizedString
		/**
		 * NOR-Dump Archiv
		 */
		archive: () => LocalizedString
		/**
		 * Controller-Diagnose
		 */
		controller: () => LocalizedString
		/**
		 * Seitenleiste ausklappen
		 */
		sidebarExpand: () => LocalizedString
		/**
		 * Seitenleiste einklappen
		 */
		sidebarCollapse: () => LocalizedString
		/**
		 * Nach Updates suchen
		 */
		checkUpdates: () => LocalizedString
		/**
		 * Update verfügbar: v{version}
		 */
		updateAvailable: (arg: { version: unknown }) => LocalizedString
		/**
		 * Immer im Vordergrund
		 */
		pinOn: () => LocalizedString
		/**
		 * Immer im Vordergrund deaktivieren
		 */
		pinOff: () => LocalizedString
		/**
		 * Immer im Vordergrund: AN
		 */
		pinTitleOn: () => LocalizedString
		/**
		 * Immer im Vordergrund: AUS
		 */
		pinTitleOff: () => LocalizedString
		/**
		 * Helles Design aktivieren
		 */
		themeLight: () => LocalizedString
		/**
		 * Dunkles Design aktivieren
		 */
		themeDark: () => LocalizedString
		/**
		 * Sprache
		 */
		language: () => LocalizedString
		/**
		 * Update
		 */
		updateBadge: () => LocalizedString
	}
	tester: {
		/**
		 * Lichter
		 */
		lights: () => LocalizedString
		/**
		 * Vibration
		 */
		vibration: () => LocalizedString
		/**
		 * Trigger
		 */
		trigger: () => LocalizedString
		/**
		 * Audio
		 */
		audio: () => LocalizedString
		/**
		 * IMU
		 */
		imu: () => LocalizedString
		/**
		 * Touchpad
		 */
		touchpad: () => LocalizedString
	}
}

export type Formatters = {}
